#!/bin/bash

xsetroot -cursor_name left_ptr
sxhkd &
$HOME/.config/bspwm/scripts/configure_screens.sh &
$HOME/.config/polybar/launch.sh &
picom --experimental-backends --backend glx &

# Monitors
bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor DisplayPort-1 -d 6 7 8 9 0

# Set wallpapers
feh --bg-scale ~/Pictures/Wallpaper/wallhaven-z8dg9y.png ~/Pictures/Wallpaper/wallhaven-z8dg9ypng

# BSPWM Configuration
bspc config border_width 0
bspc config window_gap 5
bscp config -m DisplayPort-0 top_padding 0
bscp config -m DisplayPort-1 top_padding 0
bscp config bottom_padding 0
bscp config left_padding 9
bscp config right_padding 9
bspc config split_ratio 0.52
bspc config focus_follows_pointer true
bspc config automatic_scheme spiral

#bscp config top_monocle_padding 0
#bscp config left_monocle_padding 0
#bscp config right_monocle_padding 0
#bscp config bottom_monocle_padding 0
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on

# Move to Desktop 1
bscp desktop -f 1
